name: Build & publish al-folio to gh-pages
on:
  push:
    branches: ["main"]      # déclenché à chaque push sur main
  workflow_dispatch:        # bouton “Run workflow” manuel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'          # ou 3.1 si le bundle l’exige
          bundler-cache: true          # ICI c'est OK : peaceiris n’utilise pas v3

      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec jekyll build -d _site

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages     # branche cible (créée auto)
          force_orphan: true           # branche propre, sans historique
